export const TYPING_SYSTEMS = [
  // ─── MBTI ───────────────────────────────────────────────
  {
    slug: "mbti",
    name: "MBTI",
    description: "Myers-Briggs Type Indicator — 16 personality types based on Jungian cognitive functions",
    types: [
      { value: "ISTJ", label: "ISTJ — The Inspector", description: "Practical, fact-minded, and responsible" },
      { value: "ISFJ", label: "ISFJ — The Protector", description: "Warm, caring, and conscientious" },
      { value: "INFJ", label: "INFJ — The Advocate", description: "Idealistic, principled, and compassionate" },
      { value: "INTJ", label: "INTJ — The Architect", description: "Strategic, logical, and independent" },
      { value: "ISTP", label: "ISTP — The Craftsman", description: "Bold, practical, and hands-on" },
      { value: "ISFP", label: "ISFP — The Artist", description: "Gentle, sensitive, and creative" },
      { value: "INFP", label: "INFP — The Mediator", description: "Poetic, kind, and altruistic" },
      { value: "INTP", label: "INTP — The Thinker", description: "Innovative, logical, and abstract" },
      { value: "ESTP", label: "ESTP — The Persuader", description: "Energetic, perceptive, and daring" },
      { value: "ESFP", label: "ESFP — The Performer", description: "Spontaneous, enthusiastic, and entertaining" },
      { value: "ENFP", label: "ENFP — The Champion", description: "Creative, enthusiastic, and free-spirited" },
      { value: "ENTP", label: "ENTP — The Debater", description: "Quick-witted, curious, and argumentative" },
      { value: "ESTJ", label: "ESTJ — The Supervisor", description: "Efficient, organized, and reliable" },
      { value: "ESFJ", label: "ESFJ — The Caregiver", description: "Social, caring, and harmony-seeking" },
      { value: "ENFJ", label: "ENFJ — The Teacher", description: "Charismatic, inspiring, and diplomatic" },
      { value: "ENTJ", label: "ENTJ — The Commander", description: "Bold, visionary, and decisive" },
    ],
    dimensions: [
      { name: "E/I", options: [{ value: "E", label: "Extraversion" }, { value: "I", label: "Introversion" }] },
      { name: "S/N", options: [{ value: "S", label: "Sensing" }, { value: "N", label: "Intuition" }] },
      { name: "T/F", options: [{ value: "T", label: "Thinking" }, { value: "F", label: "Feeling" }] },
      { name: "J/P", options: [{ value: "J", label: "Judging" }, { value: "P", label: "Perceiving" }] },
    ],
    config: {},
  },

  // ─── Enneagram ──────────────────────────────────────────
  {
    slug: "enneagram",
    name: "Enneagram",
    description: "Nine interconnected personality types based on core motivations, fears, and desires",
    types: [
      { value: "1", label: "Type 1 — The Reformer", description: "Principled, purposeful, and perfectionistic" },
      { value: "2", label: "Type 2 — The Helper", description: "Caring, generous, and people-pleasing" },
      { value: "3", label: "Type 3 — The Achiever", description: "Ambitious, adaptable, and image-conscious" },
      { value: "4", label: "Type 4 — The Individualist", description: "Creative, sensitive, and withdrawn" },
      { value: "5", label: "Type 5 — The Investigator", description: "Perceptive, innovative, and secretive" },
      { value: "6", label: "Type 6 — The Loyalist", description: "Committed, security-oriented, and anxious" },
      { value: "7", label: "Type 7 — The Enthusiast", description: "Spontaneous, versatile, and scattered" },
      { value: "8", label: "Type 8 — The Challenger", description: "Powerful, domineering, and confrontational" },
      { value: "9", label: "Type 9 — The Peacemaker", description: "Easygoing, reassuring, and complacent" },
    ],
    wings: Array.from({ length: 9 }, (_, i) => ({ value: `w${i + 1}`, label: `wing ${i + 1}` })),
    config: {},
  },

  // ─── Big Five (OCEAN) ───────────────────────────────────
  {
    slug: "big-five",
    name: "Big Five (OCEAN)",
    description: "Five broad personality dimensions — Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism",
    dimensions: [
      { name: "Openness", options: [{ value: "0-100", label: "0-100 scale" }] },
      { name: "Conscientiousness", options: [{ value: "0-100", label: "0-100 scale" }] },
      { name: "Extraversion", options: [{ value: "0-100", label: "0-100 scale" }] },
      { name: "Agreeableness", options: [{ value: "0-100", label: "0-100 scale" }] },
      { name: "Neuroticism", options: [{ value: "0-100", label: "0-100 scale" }] },
    ],
    config: {},
  },

  // ─── Big Five Facets (IPIP) ─────────────────────────────
  {
    slug: "big-five-facets",
    name: "Big Five Facets (IPIP)",
    description: "The 30 facet-level traits underlying the Big Five, from the IPIP-NEO",
    facets: [
      { dimension: "Openness", facets: [
        { value: "O1", label: "Imagination", description: "Preference for fantasy and daydreaming" },
        { value: "O2", label: "Artistic Interests", description: "Appreciation for art and beauty" },
        { value: "O3", label: "Emotionality", description: "Depth of emotional experience" },
        { value: "O4", label: "Adventurousness", description: "Desire for exploration and novelty" },
        { value: "O5", label: "Intellect", description: "Intellectual curiosity" },
        { value: "O6", label: "Liberalism", description: "Openness to new values and ideas" },
      ]},
      { dimension: "Conscientiousness", facets: [
        { value: "C1", label: "Self-Efficacy", description: "Belief in one's competence" },
        { value: "C2", label: "Orderliness", description: "Preference for organization" },
        { value: "C3", label: "Dutifulness", description: "Sense of moral obligation" },
        { value: "C4", label: "Achievement-Striving", description: "Drive for success" },
        { value: "C5", label: "Self-Discipline", description: "Ability to follow through" },
        { value: "C6", label: "Cautiousness", description: "Tendency to think before acting" },
      ]},
      { dimension: "Extraversion", facets: [
        { value: "E1", label: "Friendliness", description: "Warmth and sociability" },
        { value: "E2", label: "Gregariousness", description: "Preference for company" },
        { value: "E3", label: "Assertiveness", description: "Social dominance" },
        { value: "E4", label: "Activity Level", description: "Energy and pace of life" },
        { value: "E5", label: "Excitement-Seeking", description: "Thrill-seeking" },
        { value: "E6", label: "Cheerfulness", description: "Positive emotions" },
      ]},
      { dimension: "Agreeableness", facets: [
        { value: "A1", label: "Trust", description: "Belief in others' good intentions" },
        { value: "A2", label: "Morality", description: "Honesty and sincerity" },
        { value: "A3", label: "Altruism", description: "Generosity and helpfulness" },
        { value: "A4", label: "Cooperation", description: "Tendency to avoid conflict" },
        { value: "A5", label: "Modesty", description: "Humility" },
        { value: "A6", label: "Sympathy", description: "Tenderness and compassion" },
      ]},
      { dimension: "Neuroticism", facets: [
        { value: "N1", label: "Anxiety", description: "Tendency to worry" },
        { value: "N2", label: "Anger", description: "Tendency to experience anger" },
        { value: "N3", label: "Depression", description: "Tendency to sadness" },
        { value: "N4", label: "Self-Consciousness", description: "Embarrassment sensitivity" },
        { value: "N5", label: "Immoderation", description: "Difficulty controlling urges" },
        { value: "N6", label: "Vulnerability", description: "Stress susceptibility" },
      ]},
    ],
    config: {},
  },

  // ─── OPS (Objective Personality System) ─────────────────
  {
    slug: "ops",
    name: "OPS (Objective Personality)",
    description: "Objective Personality System — 16 MBTI types × 4 Animals (Sleep/Play/Consume/Blast) for 512+ type profiles",
    types: [
      { value: "ISTJ", label: "ISTJ", description: "Si-Te · Observer-Decider" },
      { value: "ISFJ", label: "ISFJ", description: "Si-Fe · Observer-Decider" },
      { value: "INFJ", label: "INFJ", description: "Ni-Fe · Observer-Decider" },
      { value: "INTJ", label: "INTJ", description: "Ni-Te · Observer-Decider" },
      { value: "ISTP", label: "ISTP", description: "Ti-Se · Decider-Observer" },
      { value: "ISFP", label: "ISFP", description: "Fi-Se · Decider-Observer" },
      { value: "INFP", label: "INFP", description: "Fi-Ne · Decider-Observer" },
      { value: "INTP", label: "INTP", description: "Ti-Ne · Decider-Observer" },
      { value: "ESTP", label: "ESTP", description: "Se-Ti · Observer-Decider" },
      { value: "ESFP", label: "ESFP", description: "Se-Fi · Observer-Decider" },
      { value: "ENFP", label: "ENFP", description: "Ne-Fi · Observer-Decider" },
      { value: "ENTP", label: "ENTP", description: "Ne-Ti · Observer-Decider" },
      { value: "ESTJ", label: "ESTJ", description: "Te-Si · Decider-Observer" },
      { value: "ESFJ", label: "ESFJ", description: "Fe-Si · Decider-Observer" },
      { value: "ENFJ", label: "ENFJ", description: "Fe-Ni · Decider-Observer" },
      { value: "ENTJ", label: "ENTJ", description: "Te-Ni · Decider-Observer" },
    ],
    animals: [
      { value: "Sleep", label: "Sleep", description: "Introverted, conserving energy, process-oriented" },
      { value: "Play", label: "Play", description: "Extraverted, exploring, idea-oriented" },
      { value: "Consume", label: "Consume", description: "Introverted, gathering, information-oriented" },
      { value: "Blast", label: "Blast", description: "Extraverted, executing, output-oriented" },
    ],
    coins: [
      { value: "Savior", label: "Savior", description: "The function you lead with and use naturally" },
      { value: "Demon", label: "Demon", description: "The function you struggle with overuse or misuse" },
      { value: "Tertiary", label: "Tertiary", description: "Support function, less developed" },
      { value: "Inferior", label: "Inferior", description: "Least developed, source of stress" },
      { value: "Opposing", label: "Opposing Role", description: "The function that opposes your savior" },
      { value: "CriticalParent", label: "Critical Parent", description: "Harsh inner critic voice" },
      { value: "Deceiver", label: "Deceiver", description: "The function that tricks you" },
      { value: "Child", label: "Child", description: "Playful, immature function" },
    ],
    config: {},
  },

  // ─── Berens-Nardi Interaction Styles ────────────────────
  {
    slug: "berens-nardi",
    name: "Berens-Nardi Interaction Styles",
    description: "Four core interaction styles describing how people lead, communicate, and collaborate",
    types: [
      { value: "In-Charge", label: "In-Charge", description: "Direct, decisive, results-oriented. Takes charge and drives action" },
      { value: "Chart-the-Course", label: "Chart-the-Course", description: "Strategic, visionary, future-focused. Maps out direction and purpose" },
      { value: "Get-Things-Going", label: "Get-Things-Going", description: "Energetic, inspiring, collaborative. Mobilizes people and resources" },
      { value: "Behind-the-Scenes", label: "Behind-the-Scenes", description: "Supportive, systematic, process-oriented. Ensures quality and stability" },
    ],
    config: {},
  },

  // ─── Classical Typology (4 Temperaments) ─────────────────
  {
    slug: "classical-typology",
    name: "Classical Typology (4 Temperaments)",
    description: "The ancient Greek four temperaments — sanguine, choleric, melancholic, phlegmatic",
    types: [
      { value: "Sanguine", label: "Sanguine", description: "Optimistic, social, enthusiastic, pleasure-seeking" },
      { value: "Choleric", label: "Choleric", description: "Ambitious, leader-like, short-tempered, driven" },
      { value: "Melancholic", label: "Melancholic", description: "Analytical, detail-oriented, thoughtful, prone to sadness" },
      { value: "Phlegmatic", label: "Phlegmatic", description: "Calm, easy-going, peaceful, unemotional" },
    ],
    config: {},
  },

  // ─── SHS (Gulenko's Humanitarian Socionics) ─────────────
  {
    slug: "shs-socionics",
    name: "SHS (Gulenko's Humanitarian Socionics)",
    description: "Gulenko's 16-type socionics system emphasizing intertype relations and humanitarian aspects",
    types: [
      { value: "ILE", label: "ILE — Intuitive Logical Extravert", description: "The Innovator. Seeks possibilities, generates ideas" },
      { value: "SEI", label: "SEI — Sensory Ethical Introvert", description: "The Mediator. Seeks comfort, harmony, aesthetics" },
      { value: "ESE", label: "ESE — Ethical Sensory Extravert", description: "The Enthusiast. Seeks connection, cheerfulness, activity" },
      { value: "LII", label: "LII — Logical Intuitive Introvert", description: "The Analyst. Seeks understanding, structure, principles" },
      { value: "EIE", label: "EIE — Ethical Intuitive Extravert", description: "The Actor. Seeks drama, expression, impact" },
      { value: "LSI", label: "LSI — Logical Sensory Introvert", description: "The Inspector. Seeks order, precision, control" },
      { value: "SLE", label: "SLE — Sensory Logical Extravert", description: "The Conqueror. Seeks power, territory, action" },
      { value: "IEI", label: "IEI — Intuitive Ethical Introvert", description: "The Lyricist. Seeks depth, meaning, beauty" },
      { value: "SEE", label: "SEE — Sensory Ethical Extravert", description: "The Politician. Seeks influence, pleasure, status" },
      { value: "ILI", label: "ILI — Intuitive Logical Introvert", description: "The Critic. Seeks truth, systems, foresight" },
      { value: "LIE", label: "LIE — Logical Intuitive Extravert", description: "The Entrepreneur. Seeks efficiency, progress, results" },
      { value: "ESI", label: "ESI — Ethical Sensory Introvert", description: "The Guardian. Seeks loyalty, security, principles" },
      { value: "EII", label: "EII — Ethical Intuitive Introvert", description: "The Humanist. Seeks authenticity, ethics, growth" },
      { value: "LSE", label: "LSE — Logical Sensory Extravert", description: "The Administrator. Seeks productivity, order, reliability" },
      { value: "IEE", label: "IEE — Intuitive Ethical Extravert", description: "The Advisor. Seeks potential, people, possibilities" },
      { value: "SLI", label: "SLI — Sensory Logical Introvert", description: "The Craftsman. Seeks quality, skill, practicality" },
    ],
    config: {},
  },

  // ─── SWS/WSS (Rick's Socionics / Western Socionics) ────
  {
    slug: "sws-socionics",
    name: "SWS/WSS (Rick's Western Socionics)",
    description: "Western-adapted Socionics — 16 types with MBTI-compatible naming and practical intertype dynamics",
    types: [
      { value: "ENTp", label: "ENTp — The Inventor", description: "Ne-Ti · Visionary, unconventional, idea generator" },
      { value: "ISFj", label: "ISFj — The Guardian", description: "Fi-Se · Protective, loyal, tradition-minded" },
      { value: "ESFj", label: "ESFj — The Provider", description: "Fe-Si · Warm, dutiful, community-builder" },
      { value: "INTj", label: "INTj — The Scientist", description: "Ti-Ne · Analytical, precise, systematizing" },
      { value: "INFj", label: "INFj — The Counselor", description: "Fi-Ne · Empathetic, insightful, idealistic" },
      { value: "ISTj", label: "ISTj — The Inspector", description: "Ti-Se · Detail-oriented, structured, reliable" },
      { value: "ESTp", label: "ESTp — The Operator", description: "Se-Ti · Pragmatic, resourceful, risk-taker" },
      { value: "INTp", label: "INTp — The Architect", description: "Ni-Te · Strategic, visionary, systems-thinker" },
      { value: "ENFp", label: "ENFp — The Champion", description: "Ne-Fi · Charismatic, enthusiastic, inspiring" },
      { value: "ISTp", label: "ISTp — The Craftsman", description: "Ti-Se · Hands-on, skilled, independent" },
      { value: "ESTj", label: "ESTj — The Supervisor", description: "Te-Si · Efficient, organized, authoritative" },
      { value: "INFp", label: "INFp — The Mediator", description: "Ni-Fe · Mystical, harmonious, diplomatic" },
      { value: "ENFj", label: "ENFj — The Teacher", description: "Fe-Ni · Passionate, persuasive, mentor" },
      { value: "ESFp", label: "ESFp — The Politician", description: "Se-Fi · Influential, pleasure-seeking, social" },
      { value: "ENTj", label: "ENTj — The Entrepreneur", description: "Te-Ni · Efficient, results-driven, visionary" },
      { value: "ISFp", label: "ISFp — The Guardian", description: "Fi-Se · Protective, loyal, tradition-minded" },
    ],
    config: {},
  },

  // ─── Talanovism / Axial Profile ─────────────────────────
  {
    slug: "talanovism",
    name: "Talanovism (Axial Profile)",
    description: "Russian socionic theory by Victor Talanov — types classified by leading function axes with visual-behavioral cues",
    types: [
      { value: "IL", label: "IL — Introverted Logic", description: "Ti-dom · Analytical, structured, systems-focused" },
      { value: "EL", label: "EL — Extraverted Logic", description: "Te-dom · Efficient, results-driven, pragmatic" },
      { value: "IE", label: "IE — Introverted Ethics", description: "Fi-dom · Authentic, values-driven, principled" },
      { value: "EE", label: "EE — Extraverted Ethics", description: "Fe-dom · Harmonious, expressive, group-oriented" },
      { value: "IS", label: "IS — Introverted Sensing", description: "Si-dom · Detail-oriented, routine, stability-seeking" },
      { value: "ES", label: "ES — Extraverted Sensing", description: "Se-dom · Action-oriented, physical, present-focused" },
      { value: "IN", label: "IN — Introverted Intuition", description: "Ni-dom · Visionary, future-focused, abstract" },
      { value: "EN", label: "EN — Extraverted Intuition", description: "Ne-dom · Possibility-oriented, divergent, creative" },
    ],
    config: {},
  },

  // ─── Naranjogram (Enneagram Subtypes) ───────────────────
  {
    slug: "naranjogram",
    name: "Naranjogram (Enneagram Subtypes)",
    description: "Claudio Naranjo's 27 Enneagram subtypes — each of the 9 types expressed through 3 instinctual variants",
    types: [
      { value: "1-SP", label: "Type 1 SP — Worry", description: "Perfectionism focused on personal anxiety and physical order" },
      { value: "1-SO", label: "Type 1 SO — Non-Adaptability", description: "Perfectionism projected onto social groups and ideals" },
      { value: "1-SX", label: "Type 1 SX — Zeal", description: "Perfectionism expressed through passionate intensity" },
      { value: "2-SP", label: "Type 2 SP — Privilege", description: "Helping with expectation of receiving in return" },
      { value: "2-SO", label: "Type 2 SO — Ambition", description: "Helping to gain social influence and recognition" },
      { value: "2-SX", label: "Type 2 SX — Seduction/Aggression", description: "Helping through intense one-on-one connection" },
      { value: "3-SP", label: "Type 3 SP — Security", description: "Achieving for material stability and self-worth" },
      { value: "3-SO", label: "Type 3 SO — Prestige", description: "Achieving for status, fame, and recognition" },
      { value: "3-SX", label: "Type 3 SX — Charisma", description: "Achieving through magnetic personal appeal" },
      { value: "4-SP", label: "Type 4 SP — Tenacity", description: "Individualism expressed through endurance and resilience" },
      { value: "4-SO", label: "Type 4 SO — Shame", description: "Individualism expressed through social comparison and envy" },
      { value: "4-SX", label: "Type 4 SX — Competition", description: "Individualism expressed through intense rivalrous connection" },
      { value: "5-SP", label: "Type 5 SP — Castle", description: "Withdrawal into a private, secure personal space" },
      { value: "5-SO", label: "Type 5 SO — Totem", description: "Withdrawal into intellectual communities and knowledge" },
      { value: "5-SX", label: "Type 5 SX — Confidence", description: "Withdrawal into intimate, confidential connections" },
      { value: "6-SP", label: "Type 6 SP — Warmth", description: "Security-seeking through personal warmth and affiliation" },
      { value: "6-SO", label: "Type 6 SO — Duty", description: "Security-seeking through group loyalty and obligation" },
      { value: "6-SX", label: "Type 6 SX — Strength/Beauty", description: "Security-seeking through physical power or attractiveness" },
      { value: "7-SP", label: "Type 7 SP — Keepers of the Castle", description: "Pleasure-seeking focused on preserving comfort zone" },
      { value: "7-SO", label: "Type 7 SO — Sacrifice", description: "Pleasure-seeking through social contribution (with limits)" },
      { value: "7-SX", label: "Type 7 SX — Suggestibility", description: "Pleasure-seeking through intense, novel experiences" },
      { value: "8-SP", label: "Type 8 SP — Satisfaction", description: "Control-seeking through material self-sufficiency" },
      { value: "8-SO", label: "Type 8 SO — Solidarity", description: "Control-seeking through group alliances and protection" },
      { value: "8-SX", label: "Type 8 SX — Possession", description: "Control-seeking through intense possession of others" },
      { value: "9-SP", label: "Type 9 SP — Appetite", description: "Peace-seeking through habitual routines and consumption" },
      { value: "9-SO", label: "Type 9 SO — Participation", description: "Peace-seeking through merging with group activities" },
      { value: "9-SX", label: "Type 9 SX — Fusion", description: "Peace-seeking through merging with another person" },
    ],
    config: {},
  },

  // ─── RH (Riso-Hudson Enneagram) ─────────────────────────
  {
    slug: "riso-hudson",
    name: "Riso-Hudson Enneagram (RHETI)",
    description: "The Riso-Hudson Enneagram adds 9 levels of health per type, from integrated (healthy) to pathological (unhealthy)",
    types: [
      { value: "1", label: "Type 1 — The Reformer", description: "Principled, purposeful, perfectionistic" },
      { value: "2", label: "Type 2 — The Helper", description: "Caring, generous, people-pleasing" },
      { value: "3", label: "Type 3 — The Achiever", description: "Ambitious, adaptable, image-conscious" },
      { value: "4", label: "Type 4 — The Individualist", description: "Creative, sensitive, withdrawn" },
      { value: "5", label: "Type 5 — The Investigator", description: "Perceptive, innovative, secretive" },
      { value: "6", label: "Type 6 — The Loyalist", description: "Committed, security-oriented, anxious" },
      { value: "7", label: "Type 7 — The Enthusiast", description: "Spontaneous, versatile, scattered" },
      { value: "8", label: "Type 8 — The Challenger", description: "Powerful, domineering, confrontational" },
      { value: "9", label: "Type 9 — The Peacemaker", description: "Easygoing, reassuring, complacent" },
    ],
    levels: [
      { value: "L1", label: "Level 1 — Liberation", description: "Fully integrated, healthy expression" },
      { value: "L2", label: "Level 2 — Psychologically Healthy", description: "Positive, balanced expression" },
      { value: "L3", label: "Level 3 — Socially Valuable", description: "Constructive, contributing expression" },
      { value: "L4", label: "Level 4 — Average: Social Role", description: "Fitting into expected social roles" },
      { value: "L5", label: "Level 5 — Average: Interpersonal Control", description: "Managing others to feel secure" },
      { value: "L6", label: "Level 6 — Average: Overcompensation", description: "Exaggerated type patterns" },
      { value: "L7", label: "Level 7 — Unhealthy: Violation", description: "Pathological, harmful patterns emerge" },
      { value: "L8", label: "Level 8 — Unhealthy: Obsession/Compulsion", description: "Delusional, compulsive behavior" },
      { value: "L9", label: "Level 9 — Unhealthy: Pathological", description: "Destructive, self-destructive state" },
    ],
    config: {},
  },

  // ─── Beatrice Chestnut Subtypes ──────────────────────────
  {
    slug: "beatrice-chestnut",
    name: "Beatrice Chestnut Subtypes",
    description: "Beatrice Chestnut's 27 Enneagram subtypes — each type's 3 instinctual variant expressions with behavioral patterns",
    types: [
      { value: "1-SP", label: "Type 1 SP — Worry", description: "Anxiety about personal order, cleanliness, and physical perfection" },
      { value: "1-SO", label: "Type 1 SO — Non-Adaptability", description: "Rigid idealism projected onto social groups" },
      { value: "1-SX", label: "Type 1 SX — Zeal", description: "Passionate, fervent crusade for perfection" },
      { value: "2-SP", label: "Type 2 SP — Privilege", description: "I deserve special treatment because I help" },
      { value: "2-SO", label: "Type 2 SO — Ambition", description: "I will be important through being indispensable" },
      { value: "2-SX", label: "Type 2 SX — Seduction/Aggression", description: "Intense, possessive, aggressive helping" },
      { value: "3-SP", label: "Type 3 SP — Security", description: "I am what I have — material success defines me" },
      { value: "3-SO", label: "Type 3 SO — Prestige", description: "I am what others think of me — reputation is everything" },
      { value: "3-SX", label: "Type 3 SX — Charisma", description: "I am magnetic — my personal appeal opens doors" },
      { value: "4-SP", label: "Type 4 SP — Tenacity", description: "Suffering endured with perseverance and resilience" },
      { value: "4-SO", label: "Type 4 SO — Shame", description: "I am flawed, and everyone can see it" },
      { value: "4-SX", label: "Type 4 SX — Competition", description: "I will prove my uniqueness by winning" },
      { value: "5-SP", label: "Type 5 SP — Castle", description: "My home is my fortress — I need protected space" },
      { value: "5-SO", label: "Type 5 SO — Totem", description: "Knowledge shared with a select group of initiates" },
      { value: "5-SX", label: "Type 5 SX — Confidence", description: "Total trust and intimacy with a single confidant" },
      { value: "6-SP", label: "Type 6 SP — Warmth", description: "I stay safe by being warm and likable" },
      { value: "6-SO", label: "Type 6 SO — Duty", description: "I stay safe by following the rules and group expectations" },
      { value: "6-SX", label: "Type 6 SX — Strength/Beauty", description: "I stay safe by being powerful or attractive" },
      { value: "7-SP", label: "Type 7 SP — Keepers of the Castle", description: "Preserving the good life, protecting my comforts" },
      { value: "7-SO", label: "Type 7 SO — Sacrifice", description: "I give to others, but only on my terms" },
      { value: "7-SX", label: "Type 7 SX — Suggestibility", description: "I am seduced by new experiences and people" },
      { value: "8-SP", label: "Type 8 SP — Satisfaction", description: "I control my environment to ensure my needs are met" },
      { value: "8-SO", label: "Type 8 SO — Solidarity", description: "I lead and protect my people" },
      { value: "8-SX", label: "Type 8 SX — Possession", description: "I own you, body and soul" },
      { value: "9-SP", label: "Type 9 SP — Appetite", description: "I merge with my routines, food, and habits" },
      { value: "9-SO", label: "Type 9 SO — Participation", description: "I merge with the group, losing myself in the collective" },
      { value: "9-SX", label: "Type 9 SX — Fusion", description: "I merge with my partner, becoming one with them" },
    ],
    config: {},
  },

  // ─── Katherine Fauvre Tritypes ───────────────────────────
  {
    slug: "fauvre-tritypes",
    name: "Katherine Fauvre Tritypes",
    description: "Katherine Fauvre's 27 tritypes — the stacking of one type from each center (Head: 5/6/7, Heart: 2/3/4, Gut: 8/9/1)",
    types: [
      { value: "1-4-5", label: "1-4-5 — The Researcher", description: "Gut 1 · Heart 4 · Head 5" },
      { value: "1-4-6", label: "1-4-6 — The Philosopher", description: "Gut 1 · Heart 4 · Head 6" },
      { value: "1-4-7", label: "1-4-7 — The Visionary", description: "Gut 1 · Heart 4 · Head 7" },
      { value: "1-3-5", label: "1-3-5 — The Achiever", description: "Gut 1 · Heart 3 · Head 5" },
      { value: "1-3-6", label: "1-3-6 — The Organizer", description: "Gut 1 · Heart 3 · Head 6" },
      { value: "1-3-7", label: "1-3-7 — The Systems Builder", description: "Gut 1 · Heart 3 · Head 7" },
      { value: "1-2-5", label: "1-2-5 — The Mentor", description: "Gut 1 · Heart 2 · Head 5" },
      { value: "1-2-6", label: "1-2-6 — The Advocate", description: "Gut 1 · Heart 2 · Head 6" },
      { value: "1-2-7", label: "1-2-7 — The Teacher", description: "Gut 1 · Heart 2 · Head 7" },
      { value: "9-4-5", label: "9-4-5 — The Contemplative", description: "Gut 9 · Heart 4 · Head 5" },
      { value: "9-4-6", label: "9-4-6 — The Seeker", description: "Gut 9 · Heart 4 · Head 6" },
      { value: "9-4-7", label: "9-4-7 — The Gentle Spirit", description: "Gut 9 · Heart 4 · Head 7" },
      { value: "9-3-5", label: "9-3-5 — The Diplomat", description: "Gut 9 · Heart 3 · Head 5" },
      { value: "9-3-6", label: "9-3-6 — The Stabilizer", description: "Gut 9 · Heart 3 · Head 6" },
      { value: "9-3-7", label: "9-3-7 — The Peacemaker", description: "Gut 9 · Heart 3 · Head 7" },
      { value: "9-2-5", label: "9-2-5 — The Supporter", description: "Gut 9 · Heart 2 · Head 5" },
      { value: "9-2-6", label: "9-2-6 — The Harmonizer", description: "Gut 9 · Heart 2 · Head 6" },
      { value: "9-2-7", label: "9-2-7 — The Optimist", description: "Gut 9 · Heart 2 · Head 7" },
      { value: "8-4-5", label: "8-4-5 — The Maverick", description: "Gut 8 · Heart 4 · Head 5" },
      { value: "8-4-6", label: "8-4-6 — The Strategist", description: "Gut 8 · Heart 4 · Head 6" },
      { value: "8-4-7", label: "8-4-7 — The Adventurer", description: "Gut 8 · Heart 4 · Head 7" },
      { value: "8-3-5", label: "8-3-5 — The Executive", description: "Gut 8 · Heart 3 · Head 5" },
      { value: "8-3-6", label: "8-3-6 — The Commander", description: "Gut 8 · Heart 3 · Head 6" },
      { value: "8-3-7", label: "8-3-7 — The Entrepreneur", description: "Gut 8 · Heart 3 · Head 7" },
      { value: "8-2-5", label: "8-2-5 — The Protector", description: "Gut 8 · Heart 2 · Head 5" },
      { value: "8-2-6", label: "8-2-6 — The Guardian", description: "Gut 8 · Heart 2 · Head 6" },
      { value: "8-2-7", label: "8-2-7 — The Crusader", description: "Gut 8 · Heart 2 · Head 7" },
    ],
    config: {},
  },

  // ─── Enneagrammer ────────────────────────────────────────
  {
    slug: "enneagrammer",
    name: "Enneagrammer (27 Subtypes)",
    description: "Modern Enneagram community system — 27 instinctual subtypes with emphasis on practical application and growth",
    types: [
      { value: "1-SP", label: "Type 1 SP — The Worrier", description: "Perfectionism focused on personal anxiety and physical order" },
      { value: "1-SO", label: "Type 1 SO — The Idealist", description: "Perfectionism projected onto social groups" },
      { value: "1-SX", label: "Type 1 SX — The Zealot", description: "Perfectionism expressed through passionate intensity" },
      { value: "2-SP", label: "Type 2 SP — The Collector", description: "Helping with expectation of receiving in return" },
      { value: "2-SO", label: "Type 2 SO — The Ambassador", description: "Helping to gain social influence" },
      { value: "2-SX", label: "Type 2 SX — The Lover", description: "Intense, seductive, possessive helping" },
      { value: "3-SP", label: "Type 3 SP — The Star", description: "Achieving for material security and admiration" },
      { value: "3-SO", label: "Type 3 SO — The Politician", description: "Achieving for status and recognition" },
      { value: "3-SX", label: "Type 3 SX — The Charmer", description: "Achieving through magnetic personal appeal" },
      { value: "4-SP", label: "Type 4 SP — The Survivor", description: "Individualism expressed through endurance" },
      { value: "4-SO", label: "Type 4 SO — The Critic", description: "Individualism expressed through social comparison" },
      { value: "4-SX", label: "Type 4 SX — The Rival", description: "Competitive, passionate individualism" },
      { value: "5-SP", label: "Type 5 SP — The Hermit", description: "Withdrawal into a private sanctuary" },
      { value: "5-SO", label: "Type 5 SO — The Professor", description: "Withdrawal into intellectual communities" },
      { value: "5-SX", label: "Type 5 SX — The Confidant", description: "Deep one-on-one intellectual intimacy" },
      { value: "6-SP", label: "Type 6 SP — The Warm Friend", description: "Security through likability and warmth" },
      { value: "6-SO", label: "Type 6 SO — The Loyalist", description: "Security through group duty and rules" },
      { value: "6-SX", label: "Type 6 SX — The Warrior", description: "Security through strength and attractiveness" },
      { value: "7-SP", label: "Type 7 SP — The Gourmand", description: "Preserving comfort, protecting the good life" },
      { value: "7-SO", label: "Type 7 SO — The Utopian", description: "Giving to society while maintaining freedom" },
      { value: "7-SX", label: "Type 7 SX — The Sensualist", description: "Novelty-seeking through intense experiences" },
      { value: "8-SP", label: "Type 8 SP — The Survivalist", description: "Control through material self-sufficiency" },
      { value: "8-SO", label: "Type 8 SO — The Leader", description: "Control through group protection and leadership" },
      { value: "8-SX", label: "Type 8 SX — The Dominator", description: "Control through intense possession of others" },
      { value: "9-SP", label: "Type 9 SP — The Comfort Seeker", description: "Peace through routine, food, and habits" },
      { value: "9-SO", label: "Type 9 SO — The Follower", description: "Peace through merging with groups" },
      { value: "9-SX", label: "Type 9 SX — The Companion", description: "Peace through merging with a partner" },
    ],
    config: {},
  },

  // ─── Placeholder: CPT ────────────────────────────────────
  {
    slug: "cpt",
    name: "CPT (Cognitive Personality Theory)",
    description: "Fluid cognitive-process model of personality — research pending for full type list",
    types: [],
    config: { placeholder: true },
  },

  // ─── Placeholder: SCS ────────────────────────────────────
  {
    slug: "scs",
    name: "SCS",
    description: "Personality system — research pending",
    types: [],
    config: { placeholder: true },
  },

  // ─── Placeholder: CSS ────────────────────────────────────
  {
    slug: "css",
    name: "CSS",
    description: "Personality system — research pending",
    types: [],
    config: { placeholder: true },
  },

  // ─── Placeholder: SSS ────────────────────────────────────
  {
    slug: "sss",
    name: "SSS",
    description: "Personality system — research pending",
    types: [],
    config: { placeholder: true },
  },

  // ─── Placeholder: NMT ────────────────────────────────────
  {
    slug: "nmt",
    name: "NMT (Neuro-Matrix Typing)",
    description: "Brain-based personality typology — research pending",
    types: [],
    config: { placeholder: true },
  },
];

export const SYSTEM_COLORS: Record<string, string> = {
  "mbti": "bg-[#2a3f6e] text-[#8ab4f8] border-[#3a5f9e]",
  "enneagram": "bg-[#3a2a4e] text-[#d4a0f8] border-[#5a3a7e]",
  "big-five": "bg-[#1a3a2a] text-[#64ffda] border-[#2a5a4a]",
  "big-five-facets": "bg-[#1a3a2a] text-[#64ffda] border-[#2a5a4a]",
  "ops": "bg-[#2a4a3a] text-[#7ddfc0] border-[#3a6a5a]",
  "berens-nardi": "bg-[#3a3a1a] text-[#f0e68c] border-[#5a5a2a]",
  "classical-typology": "bg-[#3a2a1a] text-[#e8a87c] border-[#5a3a2a]",
  "shs-socionics": "bg-[#1a2a4a] text-[#7ca8f0] border-[#2a3a6a]",
  "sws-socionics": "bg-[#2a1a3a] text-[#c89cf0] border-[#4a2a6a]",
  "talanovism": "bg-[#1a3a3a] text-[#7de8e0] border-[#2a5a5a]",
  "naranjogram": "bg-[#4a2a2a] text-[#f0a0a0] border-[#6a3a3a]",
  "riso-hudson": "bg-[#2a2a4a] text-[#a0a0f0] border-[#3a3a6a]",
  "beatrice-chestnut": "bg-[#4a2a3a] text-[#f0a8d0] border-[#6a3a5a]",
  "fauvre-tritypes": "bg-[#2a4a2a] text-[#a0f0a0] border-[#3a6a3a]",
  "enneagrammer": "bg-[#3a2a4a] text-[#d4a0f8] border-[#5a3a7e]",
  "cpt": "bg-[#1a2234] text-[#4a5a70] border-[#2a3a4a]",
  "scs": "bg-[#1a2234] text-[#4a5a70] border-[#2a3a4a]",
  "css": "bg-[#1a2234] text-[#4a5a70] border-[#2a3a4a]",
  "sss": "bg-[#1a2234] text-[#4a5a70] border-[#2a3a4a]",
  "nmt": "bg-[#1a2234] text-[#4a5a70] border-[#2a3a4a]",
};