export const TYPING_SYSTEMS = [
  // ─── MBTI ───────────────────────────────────────────────
  {
    slug: "mbti",
    name: "MBTI",
    description: "Myers-Briggs Type Indicator — 16 personality types based on Jungian cognitive functions",
    types: [
      { value: "ISTJ", label: "ISTJ — The Inspector", description: "Practical, fact-minded, and responsible" },
      { value: "ISFJ", label: "ISFJ — The Protector", description: "Warm, caring, and conscientious" },
      { value: "INFJ", label: "INFJ — The Advocate", description: "Idealistic, principled, and compassionate" },
      { value: "INTJ", label: "INTJ — The Architect", description: "Strategic, logical, and independent" },
      { value: "ISTP", label: "ISTP — The Craftsman", description: "Bold, practical, and hands-on" },
      { value: "ISFP", label: "ISFP — The Artist", description: "Gentle, sensitive, and creative" },
      { value: "INFP", label: "INFP — The Mediator", description: "Poetic, kind, and altruistic" },
      { value: "INTP", label: "INTP — The Thinker", description: "Innovative, logical, and abstract" },
      { value: "ESTP", label: "ESTP — The Persuader", description: "Energetic, perceptive, and daring" },
      { value: "ESFP", label: "ESFP — The Performer", description: "Spontaneous, enthusiastic, and entertaining" },
      { value: "ENFP", label: "ENFP — The Champion", description: "Creative, enthusiastic, and free-spirited" },
      { value: "ENTP", label: "ENTP — The Debater", description: "Quick-witted, curious, and argumentative" },
      { value: "ESTJ", label: "ESTJ — The Supervisor", description: "Efficient, organized, and reliable" },
      { value: "ESFJ", label: "ESFJ — The Caregiver", description: "Social, caring, and harmony-seeking" },
      { value: "ENFJ", label: "ENFJ — The Teacher", description: "Charismatic, inspiring, and diplomatic" },
      { value: "ENTJ", label: "ENTJ — The Commander", description: "Bold, visionary, and decisive" },
    ],
    dimensions: [
      { name: "E/I", options: [{ value: "E", label: "Extraversion" }, { value: "I", label: "Introversion" }] },
      { name: "S/N", options: [{ value: "S", label: "Sensing" }, { value: "N", label: "Intuition" }] },
      { name: "T/F", options: [{ value: "T", label: "Thinking" }, { value: "F", label: "Feeling" }] },
      { name: "J/P", options: [{ value: "J", label: "Judging" }, { value: "P", label: "Perceiving" }] },
    ],
    config: {},
  },

  // ─── Enneagram ──────────────────────────────────────────
  {
    slug: "enneagram",
    name: "Enneagram",
    description: "Nine interconnected personality types based on core motivations, fears, and desires",
    types: [
      { value: "1", label: "Type 1 — The Reformer", description: "Principled, purposeful, and perfectionistic" },
      { value: "2", label: "Type 2 — The Helper", description: "Caring, generous, and people-pleasing" },
      { value: "3", label: "Type 3 — The Achiever", description: "Ambitious, adaptable, and image-conscious" },
      { value: "4", label: "Type 4 — The Individualist", description: "Creative, sensitive, and withdrawn" },
      { value: "5", label: "Type 5 — The Investigator", description: "Perceptive, innovative, and secretive" },
      { value: "6", label: "Type 6 — The Loyalist", description: "Committed, security-oriented, and anxious" },
      { value: "7", label: "Type 7 — The Enthusiast", description: "Spontaneous, versatile, and scattered" },
      { value: "8", label: "Type 8 — The Challenger", description: "Powerful, domineering, and confrontational" },
      { value: "9", label: "Type 9 — The Peacemaker", description: "Easygoing, reassuring, and complacent" },
    ],
    wings: Array.from({ length: 9 }, (_, i) => ({ value: `w${i + 1}`, label: `wing ${i + 1}` })),
    config: {},
  },

  // ─── Big Five (OCEAN) ───────────────────────────────────
  {
    slug: "big-five",
    name: "Big Five (OCEAN)",
    description: "Five broad personality dimensions — Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism",
    dimensions: [
      { name: "Openness", options: [{ value: "0-100", label: "0-100 scale" }] },
      { name: "Conscientiousness", options: [{ value: "0-100", label: "0-100 scale" }] },
      { name: "Extraversion", options: [{ value: "0-100", label: "0-100 scale" }] },
      { name: "Agreeableness", options: [{ value: "0-100", label: "0-100 scale" }] },
      { name: "Neuroticism", options: [{ value: "0-100", label: "0-100 scale" }] },
    ],
    config: {},
  },

  // ─── Big Five Facets (IPIP) ─────────────────────────────
  {
    slug: "big-five-facets",
    name: "Big Five Facets (IPIP)",
    description: "The 30 facet-level traits underlying the Big Five, from the IPIP-NEO",
    facets: [
      { dimension: "Openness", facets: [
        { value: "O1", label: "Imagination", description: "Preference for fantasy and daydreaming" },
        { value: "O2", label: "Artistic Interests", description: "Appreciation for art and beauty" },
        { value: "O3", label: "Emotionality", description: "Depth of emotional experience" },
        { value: "O4", label: "Adventurousness", description: "Desire for exploration and novelty" },
        { value: "O5", label: "Intellect", description: "Intellectual curiosity" },
        { value: "O6", label: "Liberalism", description: "Openness to new values and ideas" },
      ]},
      { dimension: "Conscientiousness", facets: [
        { value: "C1", label: "Self-Efficacy", description: "Belief in one's competence" },
        { value: "C2", label: "Orderliness", description: "Preference for organization" },
        { value: "C3", label: "Dutifulness", description: "Sense of moral obligation" },
        { value: "C4", label: "Achievement-Striving", description: "Drive for success" },
        { value: "C5", label: "Self-Discipline", description: "Ability to follow through" },
        { value: "C6", label: "Cautiousness", description: "Tendency to think before acting" },
      ]},
      { dimension: "Extraversion", facets: [
        { value: "E1", label: "Friendliness", description: "Warmth and sociability" },
        { value: "E2", label: "Gregariousness", description: "Preference for company" },
        { value: "E3", label: "Assertiveness", description: "Social dominance" },
        { value: "E4", label: "Activity Level", description: "Energy and pace of life" },
        { value: "E5", label: "Excitement-Seeking", description: "Thrill-seeking" },
        { value: "E6", label: "Cheerfulness", description: "Positive emotions" },
      ]},
      { dimension: "Agreeableness", facets: [
        { value: "A1", label: "Trust", description: "Belief in others' good intentions" },
        { value: "A2", label: "Morality", description: "Honesty and sincerity" },
        { value: "A3", label: "Altruism", description: "Generosity and helpfulness" },
        { value: "A4", label: "Cooperation", description: "Tendency to avoid conflict" },
        { value: "A5", label: "Modesty", description: "Humility" },
        { value: "A6", label: "Sympathy", description: "Tenderness and compassion" },
      ]},
      { dimension: "Neuroticism", facets: [
        { value: "N1", label: "Anxiety", description: "Tendency to worry" },
        { value: "N2", label: "Anger", description: "Tendency to experience anger" },
        { value: "N3", label: "Depression", description: "Tendency to sadness" },
        { value: "N4", label: "Self-Consciousness", description: "Embarrassment sensitivity" },
        { value: "N5", label: "Immoderation", description: "Difficulty controlling urges" },
        { value: "N6", label: "Vulnerability", description: "Stress susceptibility" },
      ]},
    ],
    config: {},
  },

  // ─── OPS (Objective Personality System) ─────────────────
  {
    slug: "ops",
    name: "OPS (Objective Personality)",
    description: "Objective Personality System — 16 MBTI types × 4 Animals (Sleep/Play/Consume/Blast) for 512+ type profiles",
    types: [
      { value: "ISTJ", label: "ISTJ", description: "Si-Te · Observer-Decider" },
      { value: "ISFJ", label: "ISFJ", description: "Si-Fe · Observer-Decider" },
      { value: "INFJ", label: "INFJ", description: "Ni-Fe · Observer-Decider" },
      { value: "INTJ", label: "INTJ", description: "Ni-Te · Observer-Decider" },
      { value: "ISTP", label: "ISTP", description: "Ti-Se · Decider-Observer" },
      { value: "ISFP", label: "ISFP", description: "Fi-Se · Decider-Observer" },
      { value: "INFP", label: "INFP", description: "Fi-Ne · Decider-Observer" },
      { value: "INTP", label: "INTP", description: "Ti-Ne · Decider-Observer" },
      { value: "ESTP", label: "ESTP", description: "Se-Ti · Observer-Decider" },
      { value: "ESFP", label: "ESFP", description: "Se-Fi · Observer-Decider" },
      { value: "ENFP", label: "ENFP", description: "Ne-Fi · Observer-Decider" },
      { value: "ENTP", label: "ENTP", description: "Ne-Ti · Observer-Decider" },
      { value: "ESTJ", label: "ESTJ", description: "Te-Si · Decider-Observer" },
      { value: "ESFJ", label: "ESFJ", description: "Fe-Si · Decider-Observer" },
      { value: "ENFJ", label: "ENFJ", description: "Fe-Ni · Decider-Observer" },
      { value: "ENTJ", label: "ENTJ", description: "Te-Ni · Decider-Observer" },
    ],
    animals: [
      { value: "Sleep", label: "Sleep", description: "Introverted, conserving energy, process-oriented" },
      { value: "Play", label: "Play", description: "Extraverted, exploring, idea-oriented" },
      { value: "Consume", label: "Consume", description: "Introverted, gathering, information-oriented" },
      { value: "Blast", label: "Blast", description: "Extraverted, executing, output-oriented" },
    ],
    coins: [
      { value: "Savior", label: "Savior", description: "The function you lead with and use naturally" },
      { value: "Demon", label: "Demon", description: "The function you struggle with overuse or misuse" },
      { value: "Tertiary", label: "Tertiary", description: "Support function, less developed" },
      { value: "Inferior", label: "Inferior", description: "Least developed, source of stress" },
      { value: "Opposing", label: "Opposing Role", description: "The function that opposes your savior" },
      { value: "CriticalParent", label: "Critical Parent", description: "Harsh inner critic voice" },
      { value: "Deceiver", label: "Deceiver", description: "The function that tricks you" },
      { value: "Child", label: "Child", description: "Playful, immature function" },
    ],
    config: {},
  },

  // ─── Berens-Nardi Interaction Styles ────────────────────
  {
    slug: "berens-nardi",
    name: "Berens-Nardi Interaction Styles",
    description: "Four core interaction styles describing how people lead, communicate, and collaborate",
    types: [
      { value: "In-Charge", label: "In-Charge", description: "Direct, decisive, results-oriented. Takes charge and drives action" },
      { value: "Chart-the-Course", label: "Chart-the-Course", description: "Strategic, visionary, future-focused. Maps out direction and purpose" },
      { value: "Get-Things-Going", label: "Get-Things-Going", description: "Energetic, inspiring, collaborative. Mobilizes people and resources" },
      { value: "Behind-the-Scenes", label: "Behind-the-Scenes", description: "Supportive, systematic, process-oriented. Ensures quality and stability" },
    ],
    config: {},
  },

  // ─── Classical Typology (4 Temperaments) ─────────────────
  {
    slug: "classical-typology",
    name: "Classical Typology (4 Temperaments)",
    description: "The ancient Greek four temperaments — sanguine, choleric, melancholic, phlegmatic",
    types: [
      { value: "Sanguine", label: "Sanguine", description: "Optimistic, social, enthusiastic, pleasure-seeking" },
      { value: "Choleric", label: "Choleric", description: "Ambitious, leader-like, short-tempered, driven" },
      { value: "Melancholic", label: "Melancholic", description: "Analytical, detail-oriented, thoughtful, prone to sadness" },
      { value: "Phlegmatic", label: "Phlegmatic", description: "Calm, easy-going, peaceful, unemotional" },
    ],
    config: {},
  },

  // ─── SHS (Gulenko's Humanitarian Socionics) ─────────────
  {
    slug: "shs-socionics",
    name: "SHS (Gulenko's Humanitarian Socionics)",
    description: "Gulenko's 16-type socionics system emphasizing intertype relations and humanitarian aspects",
    types: [
      { value: "ILE", label: "ILE — Intuitive Logical Extravert", description: "The Innovator. Seeks possibilities, generates ideas" },
      { value: "SEI", label: "SEI — Sensory Ethical Introvert", description: "The Mediator. Seeks comfort, harmony, aesthetics" },
      { value: "ESE", label: "ESE — Ethical Sensory Extravert", description: "The Enthusiast. Seeks connection, cheerfulness, activity" },
      { value: "LII", label: "LII — Logical Intuitive Introvert", description: "The Analyst. Seeks understanding, structure, principles" },
      { value: "EIE", label: "EIE — Ethical Intuitive Extravert", description: "The Actor. Seeks drama, expression, impact" },
      { value: "LSI", label: "LSI — Logical Sensory Introvert", description: "The Inspector. Seeks order, precision, control" },
      { value: "SLE", label: "SLE — Sensory Logical Extravert", description: "The Conqueror. Seeks power, territory, action" },
      { value: "IEI", label: "IEI — Intuitive Ethical Introvert", description: "The Lyricist. Seeks depth, meaning, beauty" },
      { value: "SEE", label: "SEE — Sensory Ethical Extravert", description: "The Politician. Seeks influence, pleasure, status" },
      { value: "ILI", label: "ILI — Intuitive Logical Introvert", description: "The Critic. Seeks truth, systems, foresight" },
      { value: "LIE", label: "LIE — Logical Intuitive Extravert", description: "The Entrepreneur. Seeks efficiency, progress, results" },
      { value: "ESI", label: "ESI — Ethical Sensory Introvert", description: "The Guardian. Seeks loyalty, security, principles" },
      { value: "EII", label: "EII — Ethical Intuitive Introvert", description: "The Humanist. Seeks authenticity, ethics, growth" },
      { value: "LSE", label: "LSE — Logical Sensory Extravert", description: "The Administrator. Seeks productivity, order, reliability" },
      { value: "IEE", label: "IEE — Intuitive Ethical Extravert", description: "The Advisor. Seeks potential, people, possibilities" },
      { value: "SLI", label: "SLI — Sensory Logical Introvert", description: "The Craftsman. Seeks quality, skill, practicality" },
    ],
    config: {},
  },

  // ─── SWS/WSS (Rick's Socionics / Western Socionics) ────
  {
    slug: "sws-socionics",
    name: "SWS/WSS (Rick's Western Socionics)",
    description: "Western-adapted Socionics — 16 types with MBTI-compatible naming and practical intertype dynamics",
    types: [
      { value: "ENTp", label: "ENTp — The Inventor", description: "Ne-Ti · Visionary, unconventional, idea generator" },
      { value: "ISFj", label: "ISFj — The Guardian", description: "Fi-Se · Protective, loyal, tradition-minded" },
      { value: "ESFj", label: "ESFj — The Provider", description: "Fe-Si · Warm, dutiful, community-builder" },
      { value: "INTj", label: "INTj — The Scientist", description: "Ti-Ne · Analytical, precise, systematizing" },
      { value: "INFj", label: "INFj — The Counselor", description: "Fi-Ne · Empathetic, insightful, idealistic" },
      { value: "ISTj", label: "ISTj — The Inspector", description: "Ti-Se · Detail-oriented, structured, reliable" },
      { value: "ESTp", label: "ESTp — The Operator", description: "Se-Ti · Pragmatic, resourceful, risk-taker" },
      { value: "INTp", label: "INTp — The Architect", description: "Ni-Te · Strategic, visionary, systems-thinker" },
      { value: "ENFp", label: "ENFp — The Champion", description: "Ne-Fi · Charismatic, enthusiastic, inspiring" },
      { value: "ISTp", label: "ISTp — The Craftsman", description: "Ti-Se · Hands-on, skilled, independent" },
      { value: "ESTj", label: "ESTj — The Supervisor", description: "Te-Si · Efficient, organized, authoritative" },
      { value: "INFp", label: "INFp — The Mediator", description: "Ni-Fe · Mystical, harmonious, diplomatic" },
      { value: "ENFj", label: "ENFj — The Teacher", description: "Fe-Ni · Passionate, persuasive, mentor" },
      { value: "ESFp", label: "ESFp — The Politician", description: "Se-Fi · Influential, pleasure-seeking, social" },
      { value: "ENTj", label: "ENTj — The Entrepreneur", description: "Te-Ni · Efficient, results-driven, visionary" },
      { value: "ISFp", label: "ISFp — The Guardian", description: "Fi-Se · Protective, loyal, tradition-minded" },
    ],
    config: {},
  },

  // ─── Talanovism / Axial Profile ─────────────────────────
  {
    slug: "talanovism",
    name: "Talanovism (Axial Profile)",
    description: "Russian socionic theory by Victor Talanov — types classified by leading function axes with visual-behavioral cues",
    types: [
      { value: "IL", label: "IL — Introverted Logic", description: "Ti-dom · Analytical, structured, systems-focused" },
      { value: "EL", label: "EL — Extraverted Logic", description: "Te-dom · Efficient, results-driven, pragmatic" },
      { value: "IE", label: "IE — Introverted Ethics", description: "Fi-dom · Authentic, values-driven, principled" },
      { value: "EE", label: "EE — Extraverted Ethics", description: "Fe-dom · Harmonious, expressive, group-oriented" },
      { value: "IS", label: "IS — Introverted Sensing", description: "Si-dom · Detail-oriented, routine, stability-seeking" },
      { value: "ES", label: "ES — Extraverted Sensing", description: "Se-dom · Action-oriented, physical, present-focused" },
      { value: "IN", label: "IN — Introverted Intuition", description: "Ni-dom · Visionary, future-focused, abstract" },
      { value: "EN", label: "EN — Extraverted Intuition", description: "Ne-dom · Possibility-oriented, divergent, creative" },
    ],
    config: {},
  },

  // ─── Naranjogram (Enneagram Subtypes) ───────────────────
  {
    slug: "naranjogram",
    name: "Naranjogram (Enneagram Subtypes)",
    description: "Claudio Naranjo's 27 Enneagram subtypes — each of the nine types expressed through the self-preservation, social or sexual instinct, after Ichazo. The descriptions follow Naranjo (27 Characters in Search of Being, 2012; Essays on the Psychology of the Enneatypes, 2017; Dramatis Personae, 2019) and Chestnut (The Complete Enneagram, 2013); the examples are Naranjo's own typings.",
    types: [
      { value: "1-SP", label: "Type 1 SP — Worry", description: "Anger turned on the self as a drive to get everything right. Ichazo called the passion anguish; Naranjo settles on worry: this One is preoccupied, checks and re-checks, plans ahead and keeps the house or the department in order, the true perfectionist of the three because the self never looks finished. Anger is most hidden here. Reaction formation turns its heat into warmth, giving a decent, over-gentle helper who forbids himself resentment, so it leaks out as irritation and self-righteousness under pressure. Often the responsible child of a chaotic family, the one who provided the stability. Where the social One already feels correct, this one feels never quite right. Naranjo's examples: Louis Pasteur, Confucius, Samuel Johnson, the butler in The Remains of the Day." },
      { value: "1-SO", label: "Type 1 SO — Non-Adaptability", description: "Ichazo's word was inadaptability; Naranjo prefers superiority, a claim to be right and to deserve the last word. Anger here is turned cold rather than warm: a rigid, aristocratic, schoolteacher character who feels already perfect, models the correct way of being for others and dominates by making them feel wrong. The passion becomes a search for moral or intellectual superiority behind an imperturbable surface. Naranjo notes the paradox that this One adapts to the world by being a misfit. Emotions were repressed early; the good child who acted older than their years. Beside the worried self-preservation One, this one makes serious mistakes because it does not doubt itself. Naranjo's examples: Abraham Lincoln, Sherlock Holmes, Jeeves." },
      { value: "1-SX", label: "Type 1 SX — Zeal", description: "Ichazo called it zeal, after animal heat; Naranjo explains it as vehemence, a hyper-desire added to whatever the person wants that makes them impatient and invasive. This is the only openly angry One, which is why Chestnut names it the counter-type. Where the other Ones perfect themselves or pose as perfect, this one sets out to perfect other people: a reformer or zealot with the entitlement of a conqueror, sure of a higher code that justifies asserting their will. Hot where the self-preservation One is warm and the social One cold, with a strong spirit of domination and conquest and a frank relationship to desire. Naranjo's examples: Martin Luther, Othello as played by Laurence Olivier." },
      { value: "2-SP", label: "Type 2 SP — Privilege", description: "Ichazo's phrase was me first, the person in the desert who claims the last of the water; Naranjo calls it privilege. Pride in the sphere of self-care becomes a child's claim to be loved simply for being, not for anything done or earned. This Two seduces the way a child seduces grown-ups: cute, playful, tender, often small or youthful in manner and even in features, and expects special treatment well past childhood. Underneath sits a demanding streak and a fear of abandonment, and this is the most fearful and ambivalent Two about actually connecting. It is the counter-type, the Two in whom pride is hardest to see. Naranjo's examples: Marie Antoinette, the child who is king of the house." },
      { value: "2-SO", label: "Type 2 SO — Ambition", description: "Pride in the sphere of the group is the satisfaction of conquering an audience. This is the adult Two, the one who wants to be someone: important, influential, on top, with the advantages that come from being above. Cultivated and competent, presenting as great or expert, this Two seeks positions of leadership and cultivates the right people, and Naranjo borrows Canetti's name-licker for the way it flatters upward. It stands above even its parents, taking the role of authority while still needing to be loved for it. The most obviously proud of the Twos, and the one most likely to be admired for accomplishments. Naranjo's examples: Oscar Wilde." },
      { value: "2-SX", label: "Type 2 SX — Seduction/Aggression", description: "Ichazo spoke of conquest and seduction; Naranjo calls this the Two par excellence, the most visibly seductive of all the types. Pride in the sphere of desire is the wish to be irresistible and to be important to one particular person, pursued through classical seduction: an attractive presentation, warmth of feeling, wooing. The appeal comes with a will to power, make love and war, so this Two is a force of nature rather than a helper, with a passionate and possessive intensity in the bond and an appetite that, asked what it wants, answers everything. Naranjo's examples: Modigliani, Lord Byron, Bizet's Carmen, Cleopatra, the Colombina of the commedia dell'arte." },
      { value: "3-SP", label: "Type 3 SP — Security", description: "Vanity in the sphere of survival is the effort to be a good, useful and efficient person, which is why Naranjo calls this the counter-type: vain about having no vanity. This Three wants to be admired but avoids seeking it openly, believing that advertising your strong points is bad form. Autonomous and self-sufficient, often having learned early to get by without support, it is the efficient workaholic in the service of security: money, position, knowing how to do things well. The tone is maternal and protective, the mind precise, though it misreads its own motives. It looks less like a Three than the other two and can pass for a One. Naranjo's example: Audrey Hepburn, and the roles she played." },
      { value: "3-SO", label: "Type 3 SO — Prestige", description: "Vanity in the sphere of the group is the passion to shine before everyone, what Naranjo describes as an internal propaganda department. This Three needs applause from all sides and manipulates its self-image to earn it, so it is the biggest chameleon and the most vain of the three. It is also the most competitive, aggressive and cold, with a corporate mentality that asks what will sell, a quick climb up any ladder and a hyperactivity Canetti drew as a gust of wind. Behind the polish sits a fear of being seen as worthless, so criticism cuts deep though it is never shown. Naranjo's examples: Franklin D. Roosevelt, Becky Sharp in Vanity Fair, Julianne in My Best Friend's Wedding." },
      { value: "3-SX", label: "Type 3 SX — Charisma", description: "Ichazo named the passion femininity or masculinity; Naranjo reads it as sex appeal, the wish to be the model man or woman who attracts. Vanity in the sphere of desire becomes the passion to please: this Three likes what others like and loses track of its own preferences, turning desire into the desire to be desired. It is the shyest of the Threes and the one that suffers most, still in touch with a frustrated thirst for love behind the smile. Rather than shining itself, it promotes and supports important others and counts their success as its own, and finds it hard to talk about itself. Naranjo's examples: Marilyn Monroe, Anna Karenina, Queen Gertrude in Hamlet." },
      { value: "4-SP", label: "Type 4 SP — Tenacity", description: "Ichazo's term was defensive action, protecting a dream of the future; Naranjo first said whatever it takes, then tenacity. This is the counter-type: envy turned into effort rather than complaint. The long-suffering Four does not cry in front of others, swallows a lot and endures without blinking, working like an ant to obtain what others have. Nothing obtained ever feels like enough, because the self-devaluation keeps running. Austere, sacrificing its own desires, often generous with help, more masochistic than dramatic, it can pass for a Three or a sexual Six. Beside the social Four who suffers and the sexual Four who makes others suffer, this one suffers in silence. Naranjo's examples: Vincent van Gogh, Jane Eyre." },
      { value: "4-SO", label: "Type 4 SO — Shame", description: "Ichazo called it shame; Naranjo reads it as self-devaluation, aggression turned on the self until it feels like chronic poisoning and inferiority. Envy in the sphere of the group makes the sufferer: shy, insecure, comparing itself with everyone and finding itself lacking, and displaying its suffering the way a child cries for its mother, so that pain becomes the way to attract affection and protection. There is comfort in melancholy, guilt about any wish, and a victim's sense that the world gives nothing. Sweet in public, this Four can be angry in intimacy, and underneath sits a fierce competitiveness it does not recognize. Naranjo's examples: Toulouse-Lautrec, Hans Christian Andersen, Heinrich Heine, Marcel Proust." },
      { value: "4-SX", label: "Type 4 SX — Competition", description: "Ichazo offered two words, competition and hate. Envy in the sphere of desire is competitive and arrogant, the envy that bites and wants to strip others of what it envies. This is the insufferable Four, the one who makes others suffer: shameless where the social Four is ashamed, it knocks on every door, insists past every frustration, demands, dramatizes and holds others in contempt while remaining intensely sensitive. Naranjo sums it up as hurt people hurting people; the pain of inferiority is thrown outward to be rid of it. Desires are taken for realities, so frustration is constant. It can be mistaken for an Eight or a sexual Two. Naranjo's examples: the Marquis de Sade, Dante, Richard III." },
      { value: "5-SP", label: "Type 5 SP — Castle", description: "Ichazo's word was refuge; Naranjo speaks of a den or sanctuary and, with Chestnut, of the castle. Avarice in the sphere of survival is the need for walls: this is the most Five-ish and most withdrawn Five, the most schizoid, who hides, limits its needs and wants so as to require nothing from anyone, and holds on to what little it has by anaesthetising desire. It acts in secret so that nothing compromises it, says yes to escape pressure and then rages inwardly, and is the least expressive of the three. Naranjo's bestiary gives it the mouse. Naranjo's examples: Franz Kafka, and the clerk José in Saramago's All the Names." },
      { value: "5-SO", label: "Type 5 SO — Totem", description: "Ichazo's word was totem, and Naranjo keeps it for a passion for what matters: lofty models, the sublime, the extraordinary, admirable experts, and the self-importance of resembling them. Avarice in the sphere of the group starts from feeling insignificant and seeks the magic of meaning instead of ordinary life. This Five relates through shared knowledge and values rather than feeling, looks toward the stars and cares little for life on earth, and is the coldest of the three, with the most pronounced indifference to its peers. Admiring where the sexual Five is iconoclastic, it can become spiritual in a way that stays in the head. Naranjo's bestiary gives it the giraffe. Naranjo's example: Charles Darwin." },
      { value: "5-SX", label: "Type 5 SX — Confidence", description: "Ichazo's word was trust, which Naranjo reads as an inordinate demand for the conditions that would make it safe to trust and love, revealing a great lack of confidence in oneself. This is the counter-type, the most sensitive, emotional and romantic Five, close enough to a Four to be mistaken for one, with a vibrant inner life that often goes into art. It searches for one person who could receive the worst of its inner world with complete equanimity, an ideal no human meets, so it moves between infatuation, disappointment and isolation, and turns possessive when love appears. It can be defiant and proud before authority where the social Five would feel guilty. Naranjo's examples: Ludwig II of Bavaria, Nijinsky, Nicholas in The Magus." },
      { value: "6-SP", label: "Type 6 SP — Warmth", description: "Ichazo spoke of heat; Naranjo prefers warmth, a familiar warmth that compensates for cold loneliness and the fear of being left. Fear in the sphere of survival is insecurity and the need for protection, so this Six seeks the benevolence of others and forms alliances of the kind I will not hurt you and you will not hurt me. A rabbit, a lamb, a teddy bear: kind at the price of inhibiting all aggression, and therefore dependent on stronger people. It doubts, questions in circles, imagines what could go wrong, tolerates ambiguity and finds it hard to say black or white. The most phobic Six, and the one that most wants the good father it did not have. Naranjo's example: the young Gandhi." },
      { value: "6-SO", label: "Type 6 SO — Duty", description: "Ichazo's word was duty; Naranjo calls this the Prussian character. Fear in the sphere of the group is answered by knowing what the rules are, and the real passion is to know what the duty is, which makes this Six analytical, reflective and normative to the point of a legislative mind. Cold, formal, precise and intolerant of ambiguity, it takes refuge in obligation and impersonal authority and can become fanatical, ideological or theoretical, too sure of things as a defence against uncertainty. Obedient and loyal to the hierarchy, the wolf with its pack, it mixes phobic and counterphobic reactions. Where the self-preservation Six is warm and permissive, this one is cool and exact. Naranjo's examples: Sigmund Freud, Immanuel Kant." },
      { value: "6-SX", label: "Type 6 SX — Strength/Beauty", description: "Ichazo's word was strength, and for women beauty; Naranjo prefers the psychoanalytic counterphobia, the flight forward in which the best defence is attack. This is the counter-type: a Six who goes against fear by becoming strong and intimidating, a barking dog, a rooster, so as not to be seen as weak. Rebellious, competitive and defiant toward authority, trusting itself more than others, it keeps its tender feelings and its vulnerability in the shadow and may not know it is afraid at all. Naranjo suggests a rivalry with, or the replacing of, a weak father. The hot Six, beside the warm and the cool ones. Naranjo's example: Michelangelo." },
      { value: "7-SP", label: "Type 7 SP — Keepers of the Castle", description: "Ichazo's phrase was keepers of the castle; Naranjo came to call it family, a search for power and protection through reciprocal alliances. Gluttony in the sphere of survival is opportunism: this is the gourmand of gourmands, the most sensual, earthy and money-minded Seven, always alert to a good deal, since the alligator that sleeps becomes a handbag. It builds a family-like network of trusted allies, a benign mafia, generous to its own and cold or exploitative toward the rest. It is also the most anti-authoritarian and irreverent Seven, sceptical of religion, with humour and business sense. Naranjo's bestiary gives it the bear. Naranjo's examples: P. T. Barnum, Tom Sawyer, Mark Twain." },
      { value: "7-SO", label: "Type 7 SO — Sacrifice", description: "Ichazo's word was sacrifice, and Naranjo explains it as a counter-gluttony: this is the counter-type, a Seven that renounces its appetite in favour of purity, service and an ideal of itself and the world. It consciously avoids exploiting anyone, gets by on little, postpones its own desires and gives with a smiling generosity that asks nothing openly, while hungering to be seen as good for its sacrifice. Enthusiasm, idealism and social skill go into projects and causes. Behind the good narcissist, as Naranjo calls it, sits guilt about the self-interest under the mask, and a habit of manipulating through enthusiasm. Naranjo's examples: Thomas More, Anton Chekhov, Francis of Assisi, Timon of Athens." },
      { value: "7-SX", label: "Type 7 SX — Suggestibility", description: "Ichazo's word was suggestibility, which Naranjo reads two ways: a dreaming capacity that confuses dreams with reality, and a capacity to bewitch and hypnotise others. Gluttony in the sphere of desire is for things of a higher world; this Seven is not earthly but heavenly, an enthusiastic dreamer who imagines something better than the desolate ordinary and looks at everything with the optimism of someone in love. Light, quick, verbal and charming, it embellishes, idealises and represses the perception of pain: I am fine, everything is fine. Rebellious, impatient and restless underneath, it is the monkey of Naranjo's bestiary. Naranjo's examples: Lope de Vega, Gigi in The Life Before Us." },
      { value: "8-SP", label: "Type 8 SP — Satisfaction", description: "Ichazo's word was satisfaction, which Naranjo finds too mild: the mark of this Eight is intolerance of any frustration of its desire, I have to have it, this is mine. Lust in the sphere of survival makes the most armed, most defended and least expressive of the Eights, pure action, a survivor who knows how to get what it needs in the hardest situations and feels omnipotent doing so. It takes the shortest path from desire to satisfaction and disqualifies whatever stands in the way; at times kindness and good intentions simply do not exist for it. Cold and strategic where the sexual Eight is loud, a wolf in sheep's clothing, the crocodile of Naranjo's bestiary. Naranjo's examples: Henry VIII, Big Daddy in Cat on a Hot Tin Roof." },
      { value: "8-SO", label: "Type 8 SO — Solidarity", description: "Ichazo's word was friendship; Naranjo, who keeps that word for the healthy thing, says complicity. This is the counter-type, the social antisocial: lust and aggression placed in the service of others, a rebel against the norms who is nonetheless loyal and protective. Naranjo's image is the child who turned tough defending the mother against the father, so its violence is solidarity with the mistreated and its demand is for justice. It often comes across as a strong good person who speaks forcefully, the least psychopathic and most friendly Eight, though its ties of friendship can shade into complicity. The only intellectual Eight, in Naranjo's account. Naranjo's examples: Genghis Khan, Fidel Castro, Martin Luther King." },
      { value: "8-SX", label: "Type 8 SX — Possession", description: "Ichazo's word was possession, and Naranjo describes a tyrannical demand on the other that is lived as an exaggerated demand for love: sexual lust takes possession through fascination and threat. This is the most intense and emotional Eight, the one that does not disguise its antisocial side and even seduces with its courage to be a bandit. Provocative and charismatic, it needs to be the centre of the scene and to have the other entirely, and its possessiveness makes it tyrannical in intimate relationships. Where the self-preservation Eight is pure action and the social Eight the thinker, this one is passion. Naranjo's example: Rembrandt, as played by Charles Laughton." },
      { value: "9-SP", label: "Type 9 SP — Appetite", description: "Ichazo's word was appetite. Sloth in the sphere of survival is comfort through the body: eating, sleeping, having, routines, tangible things to do, or in Naranjo's phrase, I eat, therefore I am. The thirst for love is turned into physical appetite and other quieter voracities. This Nine is practical and concrete, prefers experience to theory, does not put its inner life into words, and is the most solitary of the three, relaxing best alone in an activity. It can carry an unexpected force that makes it look like an Eight, and sees things in black and white. For it, Naranjo says, the question of being has been erased. Naranjo's examples: Winston Churchill, Sancho Panza." },
      { value: "9-SO", label: "Type 9 SO — Participation", description: "Ichazo's word was participation, or belonging. This is the counter-type: sloth toward the self expressed through hard work for the group. Jovial, extroverted and generous, a workaholic for others who puts the group's needs first, this Nine needs to feel part of things because underneath it does not feel part of anything. It hides its pain, does not burden anyone, lends money it will never see again and leaves its own affairs unattended with an optimism that something will turn up. Naranjo reads its ardour and its pomposity as substitutes for being. A leader who talks a lot and can become a human punching bag. Naranjo's examples: Benjamin Franklin, Wilkins Micawber in David Copperfield." },
      { value: "9-SX", label: "Type 9 SX — Fusion", description: "Ichazo's word was union, which Naranjo keeps for real love and replaces here with fusion, confluence, symbiosis. Sloth in the sphere of desire is living through another: this Nine takes on the other's opinions, feelings and agenda, I am when I am with you, because standing on its own feels too hard. Sweet, gentle, shy and unassertive, it makes no noise and wants nothing for itself, projecting all wanting onto the people it loves through a compulsive altruism, and rebels only passively when its own needs are betrayed. A true union between two people who each stand alone is precisely what it cannot manage. Naranjo's examples: Harry Truman, Eugénie Grandet." },
    ],
    config: {},
  },

  // ─── RH (Riso-Hudson Enneagram) ─────────────────────────
  {
    slug: "riso-hudson",
    name: "Riso-Hudson Enneagram (RHETI)",
    description: "The Riso-Hudson Enneagram adds 9 levels of health per type, from integrated (healthy) to pathological (unhealthy)",
    types: [
      { value: "1", label: "Type 1 — The Reformer", description: "Principled, purposeful, perfectionistic" },
      { value: "2", label: "Type 2 — The Helper", description: "Caring, generous, people-pleasing" },
      { value: "3", label: "Type 3 — The Achiever", description: "Ambitious, adaptable, image-conscious" },
      { value: "4", label: "Type 4 — The Individualist", description: "Creative, sensitive, withdrawn" },
      { value: "5", label: "Type 5 — The Investigator", description: "Perceptive, innovative, secretive" },
      { value: "6", label: "Type 6 — The Loyalist", description: "Committed, security-oriented, anxious" },
      { value: "7", label: "Type 7 — The Enthusiast", description: "Spontaneous, versatile, scattered" },
      { value: "8", label: "Type 8 — The Challenger", description: "Powerful, domineering, confrontational" },
      { value: "9", label: "Type 9 — The Peacemaker", description: "Easygoing, reassuring, complacent" },
    ],
    levels: [
      { value: "L1", label: "Level 1 — Liberation", description: "Fully integrated, healthy expression" },
      { value: "L2", label: "Level 2 — Psychologically Healthy", description: "Positive, balanced expression" },
      { value: "L3", label: "Level 3 — Socially Valuable", description: "Constructive, contributing expression" },
      { value: "L4", label: "Level 4 — Average: Social Role", description: "Fitting into expected social roles" },
      { value: "L5", label: "Level 5 — Average: Interpersonal Control", description: "Managing others to feel secure" },
      { value: "L6", label: "Level 6 — Average: Overcompensation", description: "Exaggerated type patterns" },
      { value: "L7", label: "Level 7 — Unhealthy: Violation", description: "Pathological, harmful patterns emerge" },
      { value: "L8", label: "Level 8 — Unhealthy: Obsession/Compulsion", description: "Delusional, compulsive behavior" },
      { value: "L9", label: "Level 9 — Unhealthy: Pathological", description: "Destructive, self-destructive state" },
    ],
    config: {},
  },

  // ─── Beatrice Chestnut Subtypes ──────────────────────────
  {
    slug: "beatrice-chestnut",
    name: "Beatrice Chestnut Subtypes",
    description: "Beatrice Chestnut's 27 Enneagram subtypes — each type's 3 instinctual variant expressions with behavioral patterns",
    types: [
      { value: "1-SP", label: "Type 1 SP — Worry", description: "Anxiety about personal order, cleanliness, and physical perfection" },
      { value: "1-SO", label: "Type 1 SO — Non-Adaptability", description: "Rigid idealism projected onto social groups" },
      { value: "1-SX", label: "Type 1 SX — Zeal", description: "Passionate, fervent crusade for perfection" },
      { value: "2-SP", label: "Type 2 SP — Privilege", description: "I deserve special treatment because I help" },
      { value: "2-SO", label: "Type 2 SO — Ambition", description: "I will be important through being indispensable" },
      { value: "2-SX", label: "Type 2 SX — Seduction/Aggression", description: "Intense, possessive, aggressive helping" },
      { value: "3-SP", label: "Type 3 SP — Security", description: "I am what I have — material success defines me" },
      { value: "3-SO", label: "Type 3 SO — Prestige", description: "I am what others think of me — reputation is everything" },
      { value: "3-SX", label: "Type 3 SX — Charisma", description: "I am magnetic — my personal appeal opens doors" },
      { value: "4-SP", label: "Type 4 SP — Tenacity", description: "Suffering endured with perseverance and resilience" },
      { value: "4-SO", label: "Type 4 SO — Shame", description: "I am flawed, and everyone can see it" },
      { value: "4-SX", label: "Type 4 SX — Competition", description: "I will prove my uniqueness by winning" },
      { value: "5-SP", label: "Type 5 SP — Castle", description: "My home is my fortress — I need protected space" },
      { value: "5-SO", label: "Type 5 SO — Totem", description: "Knowledge shared with a select group of initiates" },
      { value: "5-SX", label: "Type 5 SX — Confidence", description: "Total trust and intimacy with a single confidant" },
      { value: "6-SP", label: "Type 6 SP — Warmth", description: "I stay safe by being warm and likable" },
      { value: "6-SO", label: "Type 6 SO — Duty", description: "I stay safe by following the rules and group expectations" },
      { value: "6-SX", label: "Type 6 SX — Strength/Beauty", description: "I stay safe by being powerful or attractive" },
      { value: "7-SP", label: "Type 7 SP — Keepers of the Castle", description: "Preserving the good life, protecting my comforts" },
      { value: "7-SO", label: "Type 7 SO — Sacrifice", description: "I give to others, but only on my terms" },
      { value: "7-SX", label: "Type 7 SX — Suggestibility", description: "I am seduced by new experiences and people" },
      { value: "8-SP", label: "Type 8 SP — Satisfaction", description: "I control my environment to ensure my needs are met" },
      { value: "8-SO", label: "Type 8 SO — Solidarity", description: "I lead and protect my people" },
      { value: "8-SX", label: "Type 8 SX — Possession", description: "I own you, body and soul" },
      { value: "9-SP", label: "Type 9 SP — Appetite", description: "I merge with my routines, food, and habits" },
      { value: "9-SO", label: "Type 9 SO — Participation", description: "I merge with the group, losing myself in the collective" },
      { value: "9-SX", label: "Type 9 SX — Fusion", description: "I merge with my partner, becoming one with them" },
    ],
    config: {},
  },

  // ─── Katherine Fauvre Tritypes ───────────────────────────
  {
    slug: "fauvre-tritypes",
    name: "Katherine Fauvre Tritypes",
    description: "Katherine Fauvre's 27 tritypes — the stacking of one type from each center (Head: 5/6/7, Heart: 2/3/4, Gut: 8/9/1)",
    types: [
      { value: "1-4-5", label: "1-4-5 — The Researcher", description: "Gut 1 · Heart 4 · Head 5" },
      { value: "1-4-6", label: "1-4-6 — The Philosopher", description: "Gut 1 · Heart 4 · Head 6" },
      { value: "1-4-7", label: "1-4-7 — The Visionary", description: "Gut 1 · Heart 4 · Head 7" },
      { value: "1-3-5", label: "1-3-5 — The Achiever", description: "Gut 1 · Heart 3 · Head 5" },
      { value: "1-3-6", label: "1-3-6 — The Organizer", description: "Gut 1 · Heart 3 · Head 6" },
      { value: "1-3-7", label: "1-3-7 — The Systems Builder", description: "Gut 1 · Heart 3 · Head 7" },
      { value: "1-2-5", label: "1-2-5 — The Mentor", description: "Gut 1 · Heart 2 · Head 5" },
      { value: "1-2-6", label: "1-2-6 — The Advocate", description: "Gut 1 · Heart 2 · Head 6" },
      { value: "1-2-7", label: "1-2-7 — The Teacher", description: "Gut 1 · Heart 2 · Head 7" },
      { value: "9-4-5", label: "9-4-5 — The Contemplative", description: "Gut 9 · Heart 4 · Head 5" },
      { value: "9-4-6", label: "9-4-6 — The Seeker", description: "Gut 9 · Heart 4 · Head 6" },
      { value: "9-4-7", label: "9-4-7 — The Gentle Spirit", description: "Gut 9 · Heart 4 · Head 7" },
      { value: "9-3-5", label: "9-3-5 — The Diplomat", description: "Gut 9 · Heart 3 · Head 5" },
      { value: "9-3-6", label: "9-3-6 — The Stabilizer", description: "Gut 9 · Heart 3 · Head 6" },
      { value: "9-3-7", label: "9-3-7 — The Peacemaker", description: "Gut 9 · Heart 3 · Head 7" },
      { value: "9-2-5", label: "9-2-5 — The Supporter", description: "Gut 9 · Heart 2 · Head 5" },
      { value: "9-2-6", label: "9-2-6 — The Harmonizer", description: "Gut 9 · Heart 2 · Head 6" },
      { value: "9-2-7", label: "9-2-7 — The Optimist", description: "Gut 9 · Heart 2 · Head 7" },
      { value: "8-4-5", label: "8-4-5 — The Maverick", description: "Gut 8 · Heart 4 · Head 5" },
      { value: "8-4-6", label: "8-4-6 — The Strategist", description: "Gut 8 · Heart 4 · Head 6" },
      { value: "8-4-7", label: "8-4-7 — The Adventurer", description: "Gut 8 · Heart 4 · Head 7" },
      { value: "8-3-5", label: "8-3-5 — The Executive", description: "Gut 8 · Heart 3 · Head 5" },
      { value: "8-3-6", label: "8-3-6 — The Commander", description: "Gut 8 · Heart 3 · Head 6" },
      { value: "8-3-7", label: "8-3-7 — The Entrepreneur", description: "Gut 8 · Heart 3 · Head 7" },
      { value: "8-2-5", label: "8-2-5 — The Protector", description: "Gut 8 · Heart 2 · Head 5" },
      { value: "8-2-6", label: "8-2-6 — The Guardian", description: "Gut 8 · Heart 2 · Head 6" },
      { value: "8-2-7", label: "8-2-7 — The Crusader", description: "Gut 8 · Heart 2 · Head 7" },
    ],
    config: {},
  },

  // ─── Enneagrammer ────────────────────────────────────────
  {
    slug: "enneagrammer",
    name: "Enneagrammer (27 Subtypes)",
    description: "Modern Enneagram community system — 27 instinctual subtypes with emphasis on practical application and growth",
    types: [
      { value: "1-SP", label: "Type 1 SP — The Worrier", description: "Perfectionism focused on personal anxiety and physical order" },
      { value: "1-SO", label: "Type 1 SO — The Idealist", description: "Perfectionism projected onto social groups" },
      { value: "1-SX", label: "Type 1 SX — The Zealot", description: "Perfectionism expressed through passionate intensity" },
      { value: "2-SP", label: "Type 2 SP — The Collector", description: "Helping with expectation of receiving in return" },
      { value: "2-SO", label: "Type 2 SO — The Ambassador", description: "Helping to gain social influence" },
      { value: "2-SX", label: "Type 2 SX — The Lover", description: "Intense, seductive, possessive helping" },
      { value: "3-SP", label: "Type 3 SP — The Star", description: "Achieving for material security and admiration" },
      { value: "3-SO", label: "Type 3 SO — The Politician", description: "Achieving for status and recognition" },
      { value: "3-SX", label: "Type 3 SX — The Charmer", description: "Achieving through magnetic personal appeal" },
      { value: "4-SP", label: "Type 4 SP — The Survivor", description: "Individualism expressed through endurance" },
      { value: "4-SO", label: "Type 4 SO — The Critic", description: "Individualism expressed through social comparison" },
      { value: "4-SX", label: "Type 4 SX — The Rival", description: "Competitive, passionate individualism" },
      { value: "5-SP", label: "Type 5 SP — The Hermit", description: "Withdrawal into a private sanctuary" },
      { value: "5-SO", label: "Type 5 SO — The Professor", description: "Withdrawal into intellectual communities" },
      { value: "5-SX", label: "Type 5 SX — The Confidant", description: "Deep one-on-one intellectual intimacy" },
      { value: "6-SP", label: "Type 6 SP — The Warm Friend", description: "Security through likability and warmth" },
      { value: "6-SO", label: "Type 6 SO — The Loyalist", description: "Security through group duty and rules" },
      { value: "6-SX", label: "Type 6 SX — The Warrior", description: "Security through strength and attractiveness" },
      { value: "7-SP", label: "Type 7 SP — The Gourmand", description: "Preserving comfort, protecting the good life" },
      { value: "7-SO", label: "Type 7 SO — The Utopian", description: "Giving to society while maintaining freedom" },
      { value: "7-SX", label: "Type 7 SX — The Sensualist", description: "Novelty-seeking through intense experiences" },
      { value: "8-SP", label: "Type 8 SP — The Survivalist", description: "Control through material self-sufficiency" },
      { value: "8-SO", label: "Type 8 SO — The Leader", description: "Control through group protection and leadership" },
      { value: "8-SX", label: "Type 8 SX — The Dominator", description: "Control through intense possession of others" },
      { value: "9-SP", label: "Type 9 SP — The Comfort Seeker", description: "Peace through routine, food, and habits" },
      { value: "9-SO", label: "Type 9 SO — The Follower", description: "Peace through merging with groups" },
      { value: "9-SX", label: "Type 9 SX — The Companion", description: "Peace through merging with a partner" },
    ],
    config: {},
  },

  // ─── Placeholder: CPT ────────────────────────────────────
  {
    slug: "cpt",
    name: "CPT (Cognitive Personality Theory)",
    description: "Fluid cognitive-process model of personality — research pending for full type list",
    types: [],
    config: { placeholder: true },
  },

  // ─── Placeholder: SCS ────────────────────────────────────
  {
    slug: "scs",
    name: "SCS",
    description: "Personality system — research pending",
    types: [],
    config: { placeholder: true },
  },

  // ─── Placeholder: CSS ────────────────────────────────────
  {
    slug: "css",
    name: "CSS",
    description: "Personality system — research pending",
    types: [],
    config: { placeholder: true },
  },

  // ─── Placeholder: SSS ────────────────────────────────────
  {
    slug: "sss",
    name: "SSS",
    description: "Personality system — research pending",
    types: [],
    config: { placeholder: true },
  },

  // ─── Placeholder: NMT ────────────────────────────────────
  {
    slug: "nmt",
    name: "NMT (Neuro-Matrix Typing)",
    description: "Brain-based personality typology — research pending",
    types: [],
    config: { placeholder: true },
  },
];

export const SYSTEM_COLORS: Record<string, string> = {
  "mbti": "bg-[#2a3f6e] text-[#8ab4f8] border-[#3a5f9e]",
  "enneagram": "bg-[#3a2a4e] text-[#d4a0f8] border-[#5a3a7e]",
  "big-five": "bg-[#1a3a2a] text-[#64ffda] border-[#2a5a4a]",
  "big-five-facets": "bg-[#1a3a2a] text-[#64ffda] border-[#2a5a4a]",
  "ops": "bg-[#2a4a3a] text-[#7ddfc0] border-[#3a6a5a]",
  "berens-nardi": "bg-[#3a3a1a] text-[#f0e68c] border-[#5a5a2a]",
  "classical-typology": "bg-[#3a2a1a] text-[#e8a87c] border-[#5a3a2a]",
  "shs-socionics": "bg-[#1a2a4a] text-[#7ca8f0] border-[#2a3a6a]",
  "sws-socionics": "bg-[#2a1a3a] text-[#c89cf0] border-[#4a2a6a]",
  "talanovism": "bg-[#1a3a3a] text-[#7de8e0] border-[#2a5a5a]",
  "naranjogram": "bg-[#4a2a2a] text-[#f0a0a0] border-[#6a3a3a]",
  "riso-hudson": "bg-[#2a2a4a] text-[#a0a0f0] border-[#3a3a6a]",
  "beatrice-chestnut": "bg-[#4a2a3a] text-[#f0a8d0] border-[#6a3a5a]",
  "fauvre-tritypes": "bg-[#2a4a2a] text-[#a0f0a0] border-[#3a6a3a]",
  "enneagrammer": "bg-[#3a2a4a] text-[#d4a0f8] border-[#5a3a7e]",
  "cpt": "bg-[#1a2234] text-[#4a5a70] border-[#2a3a4a]",
  "scs": "bg-[#1a2234] text-[#4a5a70] border-[#2a3a4a]",
  "css": "bg-[#1a2234] text-[#4a5a70] border-[#2a3a4a]",
  "sss": "bg-[#1a2234] text-[#4a5a70] border-[#2a3a4a]",
  "nmt": "bg-[#1a2234] text-[#4a5a70] border-[#2a3a4a]",
};